### ISSUE TITLE
404 error when using the SandboxPaymentRequest

### ISSUE THREAD

**Issue by AminEsmaeily** [ZarinPal-Lab/Android-SDK-Payment#4]
I am developing an Android app with an in-app purchase feature. I use the Zarinpal library to manage the payments process. To test my code and check the responses from the Zarinpal, I used the `SandboxPaymentRequest` class, but whenever I call the `startPayment` method, it returns the -11 status code. When I dived into the `startPayment` method of the `ZarinPal` class, I got that it calls the `onFailureResponse` method with the 404 as the 'httpStatusCode' parameter.
The `SandboxPaymentRequest.getPaymentRequestURL()` returns the following URL:
**https://sandbox.zarinpal.com/pg/rest/WebGate/PaymentRequest.json**
This URL doesn't work and always returns the 404. 

What is the valid URL of the Sandbox?

**Comment by ImanX** [comment]
@AminEsmaeily Thanks for open issue. I checked it but I didn't faced out.
it is possible `ZarinPal` server had issue at time.
Regards.

**Comment by ImanX** [comment]
Not responding

**Comment by hsnmrd** [comment]
same problem when using `SandboxPaymentRequest ` 
I figure out that `payment.merchantID` is missing in my code
`merchantID` in `Sandbox` is required too, but the value is not important

**Comment by AminEsmaeily** [comment]
As @hsnmrd said, the `merchantID` in `SandboxPaymentRequest` doesn't seem to be mandatory, but in action, it is. I passed a 32 char random string and the problem solved.
